### ISSUE TITLE
I have an issue with this math 🧮

### ISSUE THREAD

**Issue by YalorMewn** [MadeofTin/mathscapes#1]
Hello old friend, I came across your lovely math repo and the staggering complexity of it is making my head hurt. Is this why we're not friends anymore? 

 Let's get coffee soon and talk it over 🌬☕️

**Comment by MadeofTin** [comment]
Of course not, let me explain... It still hurts my head. Or, at least my heart because I didn’t publish more. 🙁 Many notebooks have been scribbled.  Is this the universe’s way to tell me to revisit? 🧐🤔😲

**Comment by MadeofTin** [comment]
And of course, yes to yalor coffee time 😌
